### PR TITLE
allow user to provide custom folder name

### PR DESCRIPTION
**Pull request by godot**
- deploy
 - sync

**customize-path**

### CODE REVIEW

**Comment by pavelloz** [comment]
btw. so far every module/package is depending on this directory being called marketplace_builder - does this mean every module will have to be migrated and modified to include question parameter about target directory?

**Comment by pavelloz** [comment]
Someone in a UX talk said that settings is a proof of lack of ability to make a decision, this one looks like one that will cost us a lot of time and give little value if we dont make it.

**Comment by pavelloz** [comment]
Additionally it looks like if user chooses to use different directory name he/she will be doomed to use `--path` with every command form now on.

Also documenting this will be a nightmare, imagine:

`<your project directory>/<your marketplace directory>/liquid_views/layouts/<your layout name>.liquid`

**Comment by godot** [comment]
@pavelloz agreed - closing this for now then

**Pull request closed without merging**
