### PR TITLE
Shorten command name

### PR DESCRIPTION
**Pull request by DeanmvSG**
This lets the user type in `pos`, as well as `marketplace-kit` when running commands.  To test, install package globally (or locally and then run `npm link`),  `pos` should then be available as a command in terminal and have all the same functionality that `marketplace-kit` does.

Not sure if you want this, but it seems to be more on brand and also a lot shorter/easier to type!

### CODE REVIEW

**Comment by pavelloz** [comment]
I think Ignacy already is using alias `mk` so i think length of the command is a problem, if there is no popular cli tool named `pos` im for it.

**Comment by pavelloz** [comment]
Ouh, sorry, you proposed renaming. So we cant do that like this -- thats too brutal ATM.

I thought you just added `pos` alias.

**Comment by DeanmvSG** [comment]
Both are still supported.  I did look at doing this as an alias in ZSH just on my machine, but it seems nice to do it globally for all users.  

There is already a package for [https://www.npmjs.com/package/pos](pos) but it doens't use a CLI command so shouldn't be an issue if you keep the package name as it currently is.

**Comment by pavelloz** [comment]
Both are working  because you didnt do `npm unlink` - if you get rid off old symlinks, it wont work, probably. ;)

**Comment by DeanmvSG** [comment]
Completely removed this package, check neither command worked, re-installed from my branch.  Both commands work 😀 

Again, might not the be the best way, let me know if there is a better way, or if I should just do an alias locally! 

screen shot 2018-04-24 at 12 23 51

**Comment by pavelloz** [comment]
Ouh... My bad. You added all those things, not renamed them. Got it :)

Looks good to me, lets hear at least one more voice

**Comment by kv109** [comment]
`https://www.npmjs.com/package/pos` is already taken. How about `pos-cli` or `posctl`?
I <3 the idea BTW!

**Comment by pavelloz** [comment]
This discussion is not about changing package name, but cli name exposed to the shell

**Comment by kv109** [comment]
@pavelloz I still didn't want to "steal" this `pos` name. Looks like this `pos` package is in use. Probably I'm trying to be too nice ;) Your call.

**Comment by ignacy** [comment]
Having a shorter name would definitely be useful - I hate making the same typos every time 😉 
But to be honest, the solution I'd prefer would be to just `alias pos="marketplace-kit"` in `~/.bash_profile` or equivalent config file. 

I'm not sure that I know of a package that does provide more than one name, and having those names completely different would probably be a bit confusing, right?

**Comment by pavelloz** [comment]
@kv109 
There can be python cli tool called pos, brew package called pos and pos piece of software on sourceforge. There is always risk of conflicts, until you land on something long and hard to use as we did.

@ignacy thats my concern too. Thats why aliasing on client side is safer (it protects from both conflict and confusion), maybe alias recommendation would be less confusing for users.

**Comment by DeanmvSG** [comment]
@pavelloz  A small update to readme could work? `alias` is basically the same for most shells? (I'm using zsh) 

Sounds like this change is a bit over the top for being able to be done elsewhere!

**Comment by pavelloz** [comment]
Yep, lets go with alias education in tips and tricks in documentation instead of taking second cli command.

**Pull request closed without merging**
